# Generated by Django 5.2 on 2025-04-09 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessions', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_nsfw',
            field=models.BooleanField(default=False),
        ),
    ]
